# Generated by Django 4.2.1 on 2023-06-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('vehicleId', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Placa', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('driverId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=150)),
                ('Fecha_Nacimiento', models.DateField()),
                ('vehicleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuber.vehiculo')),
            ],
        ),
    ]
