# Generated by Django 4.2.1 on 2023-06-03 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodoPago',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='Fecha_Nacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Placa',
            new_name='placa',
        ),
        migrations.CreateModel(
            name='viaje',
            fields=[
                ('tripId', models.AutoField(primary_key=True, serialize=False)),
                ('direccionOrigen', models.CharField(max_length=500)),
                ('direccionDestino', models.CharField(max_length=500)),
                ('fechaViaje', models.DateField()),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuber.conductor')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pasajero_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuber.metodopago')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='auditory_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
