# Generated by Django 4.2.1 on 2023-06-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuber', '0002_metodopago_rename_apellido_conductor_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='driverId',
            new_name='id_driver',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='vehicleId',
            new_name='id_vehicle',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='paymentId',
            new_name='id_payment',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='pasajero_pago',
            old_name='paymentId',
            new_name='id_payment',
        ),
        migrations.RenameField(
            model_name='pasajero_pago',
            old_name='userId',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='vehicleId',
            new_name='id_vehicle',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='direccionDestino',
            new_name='direccion_destino',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='direccionOrigen',
            new_name='direccion_origen',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='fechaViaje',
            new_name='fecha_viaje',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='driverId',
            new_name='id_driver',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='tripId',
            new_name='id_trip',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='userId',
            new_name='id_user',
        ),
    ]
