# Generated by Django 4.2.1 on 2023-06-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuber', '0003_rename_fechanacimiento_conductor_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditory_log',
            old_name='id_user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='id_driver',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='id_vehicle',
            new_name='vehicle_id',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='id_payment',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='pasajero_pago',
            old_name='id_payment',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='pasajero_pago',
            old_name='id_user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='id_vehicle',
            new_name='vehicle_id',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='id_driver',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='id_trip',
            new_name='trip_id',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
