# Generated by Django 4.2.1 on 2023-06-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuber', '0004_rename_id_user_auditory_log_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='pasajero_pago',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='pasajero_pago',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='user_id',
            new_name='user',
        ),
    ]
