# Generated by Django 4.2.1 on 2023-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuber', '0005_rename_vehicle_id_conductor_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
